### ISSUE TITLE
suitable for app store ?

### ISSUE THREAD

**Issue by weepy** [shazron/WKWebViewFIleUrlTest#1]
is this approach suitable for delivering to the app store ?

**Comment by shazron** [comment]
Not sure what you mean by "approach". This is just a test app to demonstrate the WKWebView bug.

**Comment by weepy** [comment]
Sorry me being stupid   

I noticed that it works via /tmp but was wondering if you had an idea about how suitable that was for distribution

**Comment by shazron** [comment]
It shouldn't be a problem. Just add code so you don't copy it to tmp every single time you load (or do an rsync to copy or remove changes). If you don't, launching might take longer than you desire because of the copying (negligible for small payloads).
