### ISSUE TITLE
Cannot load external resources like javascript, xml file

### ISSUE THREAD

**Issue by chipbk10** [shazron/WKWebViewFIleUrlTest#3]
I've tried your approach. The html resource in your demo application is quite simple, just only one file "index.html". My local resource is quite complex, the html file needs to include some other external javascript file, and read data from xml file. It seems that with your approach, it cannot load the external resources.

Could you please double check on that?

**Comment by shazron** [comment]
Yeah this is the Apple bug fix we are waiting for, see my latest commits testing for it. Literally nothing I can do
