### ISSUE TITLE
Works from tmp

### ISSUE THREAD

**Issue by lucasgunn** [shazron/WKWebViewFIleUrlTest#5]
Hi Shazron,

I've been following this issue, and thought I would re-test against iOS 8.4 - it seems to work from the tmp choice, but only that one.

**Comment by shazron** [comment]
Thanks! Yup I know. It's been fixed since iOS 9 beta 2 with the new API function.

**Comment by lucasgunn** [comment]
Cool, thanks.

**Comment by xilin** [comment]
I tested the project using a device running iOS 8.0, all cases cannot work
